spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#  druid:
#    initial-size: 5   # 初始化大小
#    min-idle: 5       # 最小空闲连接个数
#    max-active: 20    # 最大连接个数
#    max-wait: 60000   # 配置获取连接等待超时的时间
#    time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次监测，监测需要关闭的空闲连接，单位时毫秒
#    min-evictable-idle-time-millis: 60000       # 配置一个连接在池中最小生存的时间
#    validation-query: select 'x'                # 用来监测连接是否有效的sql，要求是一个查询语句
#    test-while-idle: true            # 建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
#    test-on-borrow: false            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
#    test-on-return: false            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
#    pool-prepared-statements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
#    max-open-prepared-statements: 20
#    filter:
#      commons-log:
#      connection-logger-name: stat,wall,log4j   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
#      stat-view-servlet:
#        url-pattern: /druid/*  # 监控页面访问路径
#        # 允许清空统计数据
#        reset-enable: true
#        login-username: admin
#        login-password: 123456
#          # StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
#          # deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
#          # 配置的格式
#          # <IP>
#          # 或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
#        # 24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
#        allow:
#        deny:

server:
  port: 8088
  #url:192.168.1.1
  # logging.config=classpath:log4j2_dev.xml
logging:
  config: classpath:log4j2.yml


person:
  name: yaliu
  age: 18

customer: {name: customer, age: 18}

username: yaliu

address:
  - beijing
  - shanghai

